### ISSUE TITLE
How to get the value for oauth_verifier in Step 3 (Getting an Access Token)?

### ISSUE THREAD

**Issue by varunpal7** [reneraab/node-twitter-api#36]
Unable to get the value for oaut_verifier .As a result of this not able to run the below function which needs the oauth_verifier as a parameter.

Twitter.prototype.getAccessToken = function(requestToken, requestTokenSecret, oauth_verifier, callback) {
	this.oa.getOAuthAccessToken(requestToken, requestTokenSecret, oauth_verifier, function(error, oauthAccessToken, oauthAccessTokenSecret, results) {
		if (error) {
			callback(error);
		} else {
			console.log("HIIIIII");
			callback(null, oauthAccessToken, oauthAccessTokenSecret, results);
		}
	});
};

Now in the begining of step 3 it is written that he url from step 2 will redirect and provide us with the value for oauth_verifier ,but when we are trying to get the rediret url it is returning us html content and we are not getting a oauth_verifier in that.

**Comment by reneraab** [comment]
The URL "https://twitter.com/oauth/authenticate?oauth_token=[requestToken]" needs to be opened by the user (in a browser). When the user logs in, the user will be redirected to the callback URL (specified in step 1). You need to have some kind of web server accepting requests made to this URL and then use the content of the GET variables oauth_token and oauth_verifier to get your access token (see README step 3).

I don't understand what you mean by saying that the callback URL is giving you html content. This URL should be owned by you and you are the one putting the content there.
The oauth_verifier ist part of the redirect URL (e.g. yourdomain.tld/callback?oauth_verifier=[value of oauth_verifier]&oauth_token=[...]).

If you still have questions concerning the authentication process, please read https://dev.twitter.com/web/sign-in/implementing - especially step 2 - and other related pages on the Twitter Developers page.

You can also try and use PIN-based authorization if you are building an application that is not web-based. See https://dev.twitter.com/oauth/pin-based for more information.

**Comment by redcap3000** [comment]
I think he is referring to a totally server-side flow which I am also attempting to implement to issue search queries; but not modify or access anyones 'personalized' twitter data. Perhaps twitters v 1.1 api attempts to prevent this so using a browser emulator like casper may be a work-around. Because its not clear how long access keys last.

**Comment by reneraab** [comment]
Oh, ok. Then you should probably take a look at https://dev.twitter.com/oauth/application-only. Currently this is not supported by node-twitter-api. When using the application-only authentication, all requests to Twitter just include the Authorization header and don't need to be signed (as opposed to the "user requests"). So you are probably better off implementing it yourself (see the above link for documentation) as node-twitter-api would have to be totally rewritten to support this.

I will close this issue because the problem does not directly relate to node-twitter-api. However, if you do still have questions, feel free to re-open it. :)
